### ISSUE TITLE
ebook-convert not found

### ISSUE THREAD

**Issue by DahlitzFlorian** [DahlitzFlorian/docker-calibre#1]
The commands/applications `ebook-convert` and `calibre-smtp` as all other calibre commands are not found, even though they were added to `$PATH`.

**Comment by inductor** [comment]
Hi! Did you try to set the PATH using `ENV` in Dockerfile?
https://stackoverflow.com/questions/27093612/in-a-dockerfile-how-to-update-path-environment-variable

**Comment by DahlitzFlorian** [comment]
Hi! Thanks for the suggestion! Anyway, I added it, but it didn't solved the issue.

**Comment by inductor** [comment]
I guess that's because several packages are missing to execute them.

https://github.com/ljnelson/docker-calibre-alpine would be somewhere to have a look :)
